### ISSUE TITLE
With hash collisions, equality sensitive to insertion order

### ISSUE THREAD

**Issue by glchapman** [mvkara/fsharp-hashcollections#19]
For example, the following prints false (compiled with HashCollections 0.3.0):
```
    let set1 = HashSet.ofSeq [1UL; 0x200000003UL]
    let set2 = HashSet.ofSeq [0x200000003UL; 1UL]
    printfn "%A" (set1 = set2)
```
(The two numbers added both hash to 1).

**Comment by mvkara** [comment]
Thanks for reporting the issue @glchapman and the reproduce code. Will take a look shortly.

**Comment by mvkara** [comment]
This has been fixed. https://github.com/mvkara/fsharp-hashcollections/pull/20
